module.exports = {
  PORT: process.env.PORT,
  MONGODB_CONNECTION_STRING: process.env.MONGODB_CONNECTION_STRING,
  CMC_API_KEY: process.env.CMC_API_KEY,
  ELASTIC_APM_SERVICE_NAME: process.env.ELASTIC_APM_SERVICE_NAME,
  ELASTIC_APM_SERVER_URL: process.env.ELASTIC_APM_SERVER_URL,
};
