module.exports = {
  PORT: process.env.PORT,
  MONGODB_CONNECTION_STRING: process.env.MONGODB_CONNECTION_STRING,
  OKX_MASTER_API_KEY: process.env.OKX_MASTER_API_KEY,
  OKX_MASTER_SECRET_KEY: process.env.OKX_MASTER_SECRET_KEY,
  OKX_MASTER_PASSPHRASE: process.env.OKX_MASTER_PASSPHRASE,
  AMQP_URL: process.env.AMQP_URL,
  ELASTIC_APM_SERVICE_NAME: process.env.ELASTIC_APM_SERVICE_NAME,
  ELASTIC_APM_SERVER_URL: process.env.ELASTIC_APM_SERVER_URL,
};
