module.exports = {
  PORT: process.env.PORT,
  AMQP_URL: process.env.AMQP_URL,
  EMAIL_ID: process.env.EMAIL_ID,
  SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
  TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
  TWILIO_PHONE_NUMBER: process.env.TWILIO_PHONE_NUMBER,
  ELASTIC_APM_SERVICE_NAME: process.env.ELASTIC_APM_SERVICE_NAME,
  ELASTIC_APM_SERVER_URL: process.env.ELASTIC_APM_SERVER_URL,
};
